### ISSUE TITLE
Validation does not work in schema with two fields

### ISSUE THREAD

**Issue by bobdevries** [maximdanilchenko/aiohttp-apispec#100]
When a `Schema` only consists of two fields like

```
class ExampleSchema(Schema):
    field1 = fields.Str()
    field2 = fields.Str()
```
and is used with `many=True`, the validated data will result in a faulty dictionary.

For example, validating `[{field1 :"hello", field2 : "world"}, {field1 :"hi", field2 : "venus"}]`, results in `{field1: field2}`. The error lies in the way, the `results` dictionary is updated.

https://github.com/maximdanilchenko/aiohttp-apispec/blob/4697941a292b5b3600fd58217a420c5f402b1b05/aiohttp_apispec/middlewares.py#L40

**Comment by maximdanilchenko** [comment]
@bobdevries can you please give example of code that produces this issue? As I see your request json body root element is list, not object?

**Comment by kiforchuk** [comment]
Resolved by merging https://github.com/maximdanilchenko/aiohttp-apispec/pull/101 into master
