### ISSUE TITLE
aiohttp-apispec 2.2.1 provides a version of Swagger-UI that is vulnerable to XSS

### ISSUE THREAD

**Issue by rhertzog** [maximdanilchenko/aiohttp-apispec#113]
In Debian, we have a webservice using aiohttp-apispec, it's available here:
https://janitor.debian.net/api/docs

That URL is vulnerable to cross-site scripting issue as proven by the following sample URLs:
* https://janitor.debian.net/api/docs?url=https://jumpy-floor.surge.sh/test.yaml should show an alert box
* https://janitor.debian.net/api/docs?configUrl=https://tearful-earth.surge.sh/test.json should show you a sample phishing page

This is because aiohttp-apispec is embedding an old version of Swagger-UI that is vulnerable to XSS. Can you please update the version of Swagger-UI that you are embedding and make a new release?

I don't have currently the details of what version is fixing the issue and I can't find anything obvious in the recent history.

Thank you in advance.

/cc @jelmer

**Comment by maximdanilchenko** [comment]
Closed by @slymit with #114. Released in 2.2.2 and 3.0.0b1
