### ISSUE TITLE
Release aiohttp-apispec to pypi

### ISSUE THREAD

**Issue by kiforchuk** [maximdanilchenko/aiohttp-apispec#117]
@maximdanilchenko Does anything block new release on pypi?
Could you please publish both 2.2.2 and 3.0.0 versions? 3.0.0 may have "pre-release" tag if you have any concerns

**Comment by kiforchuk** [comment]
@maximdanilchenko could you please take a look when you'll have time?

**Comment by maximdanilchenko** [comment]
Done. Sorry for slowness😞
