### ISSUE TITLE
Incorrect behavior in aiohttp_apispec_middleware

### ISSUE THREAD

**Issue by borisrozumnuk** [maximdanilchenko/aiohttp-apispec#18]
My problem is if I add `aiohttp_apispec_middleware` in my `MIDDLEWARES` list, exception catching middlewares know nothing about exceptions in apispec
```
MIDDLEWARES = [
    ...,
    exception_middleware,  # Catch exception, format it and respond to client
    SentryMiddleware(settings.SENTRY),  # Send exception data to sentry
    ...,
    aiohttp_apispec_middleware
]
```

In my opinion, the problem is in this piece of code:
```
middlewares.py: 40
except web.HTTPClientError as error:
    return (error_handler or _default_error_handler)(error)
```

If I change it to:
```
except web.HTTPClientError as error:
    raise error
```
everything works correctly

If you agree that this is the problem, I can  make PR with fix.

**Comment by maximdanilchenko** [comment]
Yes, that's a good idea. I agree that this peace of code is a real problem.
But in this case I think exception catching will be redundant. So we can remove it fully.

**Comment by maximdanilchenko** [comment]
I thought about it for a while. In my opinion we should make a new middleware - just a copy of old one with your improvements (name it ```validation_middleware``` for instance). 
Old one will be deprecated and removed after some time. Because some users can use it already and we can break somthing there.

**Comment by maximdanilchenko** [comment]
Uploaded to pypi [aiohttp-apispec 0.7.0](https://pypi.org/project/aiohttp-apispec/)
