### ISSUE TITLE
Avoid validating GET requests against schema

### ISSUE THREAD

**Issue by ccrisan** [maximdanilchenko/aiohttp-apispec#26]
My (simplified) code looks something like this:

    @docs(summary='Reveal details about a specific user')
    @use_kwargs(UserSchema())
    @marshal_with(UserSchema())
    def get_user(request):
        user_id = request.match_info['id']
        user = User.select().where(User.id == user_id).get()

        return web.json_response(UserSchema().dump(user))

The view is obviously meant to be requested via GET and the library should not validate any kind of data. Nevertheless, the `validation_middleware` middleware will see that this view has `__schemas__` and will apply validations, throwing missing fields errors for all required fields.

What am I doing wrong here?

**Comment by maximdanilchenko** [comment]
First of all, why do you use `@use_kwargs` here? I see they it is not needed in your example. So just throw it away and that's all.
As for validation - all http methods can have query params. `validation_middleware` (actually `webargs`'s parser) can search there too. So you can use `use_kwargs` with GET and DELETE queries and pass the `location` param there. Like so:
```python
class BaseRequest(MySchema):
    limit = fields.Int(
        validate=validate.Range(min=1, max=1000),
        required=False,
    )
    offset = fields.Int(
        validate=validate.Range(min=1, max=1000),
        required=False,
    )

@docs(tags=['users'], summary='get users')
@use_kwargs(BaseRequest(strict=True), locations=['query'])
@marshal_with(UsersList())
async def get_users(self, request: web.Request) -> web.Response:
    limit = request['data']['limit']
    offset = request['data']['offset']
    users = User.select().limit(limit).offset(offset).get()
    return web.json_response({'users': users})
```
So this query will be valid with this view:
`GET /users?limit=100&offset=10`

P.S. Also use `strict=True` param in schemas in `use_kwargs`.

**Comment by ccrisan** [comment]
@maximdanilchenko you're right: I shouldn't be using `use_kwargs` for this particular view.

> P.S. Also use strict=True param in schemas in use_kwargs.

I'm using marshmallow 3.x and it seems `strict` argument was removed and it became the default behaviour.

Thanks for your quick response and for your work!
