### ISSUE TITLE
Any plans on using more recent version of swagger ui?

### ISSUE THREAD

**Issue by juraseg** [maximdanilchenko/aiohttp-apispec#27]
It has some bugs fixed. For example a bug with forward slash in tag:
https://github.com/swagger-api/swagger-ui/issues/2372

**Comment by juraseg** [comment]
Hi
sorry, I created issue in wrong repo :)

**Comment by maximdanilchenko** [comment]
@juraseg, check latest version.
https://github.com/maximdanilchenko/aiohttp-apispec/blob/master/README.md#3x-swaggerui-version

**Comment by juraseg** [comment]
hey @maximdanilchenko 
this looks great! there is a small bug when you try using swagger_path="/docs/ui" instead of "/docs".

I've created a pull request with fix: https://github.com/maximdanilchenko/aiohttp-apispec/pull/43
