### ISSUE TITLE
Use definitions instead of schema inlining

### ISSUE THREAD

**Issue by PoisonousJohn** [maximdanilchenko/aiohttp-apispec#34]
Hi, i'm using 0.7.5 version, and it is inlining all schemas in spec (not sure about newer versions).
It would be much better to utilize definitions.

Is it possible considering current architecture?
Would be great at least to have an option to register mappings between definition and schema.

**Comment by maximdanilchenko** [comment]
Hi, @PoisonousJohn 
Could you please give some code examples of how you see it?

**Comment by PoisonousJohn** [comment]
At the [apispec docs](https://apispec.readthedocs.io/en/stable/) there's an example of registering schemas:
```python
spec.definition('Category', schema=CategorySchema)
spec.definition('Pet', schema=PetSchema)
```
which goes to the definitions section of OpenAPI:
```json
{
  "info": {
    "title": "Swagger Petstore",
    "version": "1.0.0"
  },
  "swagger": "2.0",
  "paths": {
    "/random": {
      "get": {
        "description": "A cute furry animal endpoint.",
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Pet"
            },
            "description": "A pet to be returned"
          }
        },
      }
    }
  },
  "definitions": {
    "Pet": {
      "properties": {
        "category": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Category"
          }
        },
        "name": {
          "type": "string"
        }
      }
    },
    "Category": {
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      }
    }
  },
}
``` 
I thought that use_kwargs and marshal_with may help to associate schema definitions with specific routes, which will result in a smaller swagger.json.

Also if I use swagger-codegen, I'll get dulicated models per route, instead of the one, reusable.
I'm just not sure that it's possible to gather this schema mappings automatically, if not, the option to add it manually via spec would be ok too.

**Comment by maximdanilchenko** [comment]
Ok, so for `aiohttp` I see that API smth like that:
1. Your definitions must be registered in `aiohttp` app with `setup_aiohttp_apispec` function.
```python
# Somewhere in aiohttp app factory
setup_aiohttp_apispec(...,
                      # here we can add definitions initialization and use them as usual
                      definitions={'SomeSchema': SomeSchema},
                      ...
)
```
2. After that we can use this definitions in our methods:
```python
# Somewhere in views
@docs()
@marshal_with(definition='SomeSchema')
async def index(request):
    # use request['data']
```

**Comment by PoisonousJohn** [comment]
Wouldn't it be more convenient to leave 2 part as it is right now.
So you use

```
@marshal_with(SomeSchema, 200, 'Description')
```
But since we've registered definitions upfront, we may just map Schema class to its definition name. Though mapping will be a bit inverted comparing to the map we've specified at the initialization.

This will maintain compatibility, and automatically improve generated json for all existent project. All you will need to do for that is just to set up a mapping at the initializatoin stage.

What do you think?

**Comment by maximdanilchenko** [comment]
Yes, it is possible, but only in cases when you use one object (class or instance) for those definitions. Like this:
```python
schema = MySchema(strict=True)

@docs()
@marshal_with(schema) # or just MySchema
async def func1(request):
    ...

@docs()
@marshal_with(schema) # or just MySchema
async def func2(request):
    ...
```
And not this:

```python
@docs()
@marshal_with(MySchema(strict=True))
async def func1(request):
    ...

@docs()
@marshal_with(MySchema(strict=True))
async def func2(request):
    ...
```
I think that it is a good idea. While registering schemas we can add new one to some dict and if some routes will have common schema obj, use it instead of new copy.

**Comment by PoisonousJohn** [comment]
Sorry, I didn't deep dive in the code of your awesome project, but why isn't it possible with multiple objects?

I mean everything we need from the initial mapping is just an association of Schema class to its definition string name.

So in the end we could just check that **classes** of schemas are equal and in that case return the name of definition.

Schema objects itself in this case may be different.

**Comment by maximdanilchenko** [comment]
In case of multiple objects schemas of common class can be different because of init arguments. [See here](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/schema.py#L347). So it can lead to some errors.

**Comment by PoisonousJohn** [comment]
Oh, I see, thanks for the clarification. Anyway, I agree, it wouldn't be a problem to reuse a scheme in these decorators.

**Comment by maximdanilchenko** [comment]
Changes made in [12716dd](https://github.com/maximdanilchenko/aiohttp-apispec/commit/12716dd43f4c39c810265a9e539dff78c9a4cb78) also solved this issue. Please, check out in versions > 0.9.0
