### ISSUE TITLE
Path is no longer available in apispec > 0.39.0

### ISSUE THREAD

**Issue by voltane** [maximdanilchenko/aiohttp-apispec#37]
According to changes in apispec [here](https://apispec.readthedocs.io/en/stable/changelog.html#b1-2018-07-29) the _Path_ is no longer available, yet _aiohttp_apispec.py_ from latest version still tries to import it resulting in **ImportError: cannot import name 'Path'**. Last changes here was title as 'drop support for apispec <0.39' so it seems to be related. I dont have enough knowledge about the project to submit some PR for that.
Cheers!

**Comment by maximdanilchenko** [comment]
I made all needed changes to support apispec>=1.0.0. Available on pypi already: https://pypi.org/project/aiohttp-apispec
