### ISSUE TITLE
Unable to install the latest (0.9.1) version

### ISSUE THREAD

**Issue by mirrorrim** [maximdanilchenko/aiohttp-apispec#39]
Now there is another issue - there is no `requirements.txt` file in uploaded .gz archive - `FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'`

**Comment by maximdanilchenko** [comment]
@mirrorrim thanks a lot for those issues. I added `MANIFEST.in` file to project so such stupid issues will not occur again.. 
Also I updated latest version on pypi, again.
