### ISSUE TITLE
HEAD documentation is not generated

### ISSUE THREAD

**Issue by Meallia** [maximdanilchenko/aiohttp-apispec#50]
The documentation for HEAD is not generated.

It would be easy to allow the `AiohttpApiSpec` class and `setup_aiohttp_apispec` function to take a list of path to generate documentation for without changing the default behaviour.

I already made a patch for this issue, i'll make a pull request.

**Comment by v-v-vishnevskiy** [comment]
You can make just this `aiohttp_apispec.PATHS.add("head")` :-)

**Comment by maximdanilchenko** [comment]
There are no answer from @Meallia here and in his PR. So I think we can wait some time and I will make just like I wrote [here](https://github.com/maximdanilchenko/aiohttp-apispec/pull/51#issuecomment-491709136).
