### ISSUE TITLE
Controlling validation error output

### ISSUE THREAD

**Issue by abondar** [maximdanilchenko/aiohttp-apispec#53]
Hi

Is there any way to change default validation error code? 
As much as I see from code, right now status code is determined by `webargs` and it doesn't seem to be allowing any customisation (apart from monkey-patching `webargs.core.DEFAULT_VALIDATION_STATUS` variable)

Also some way of customising body of validation error would be nice, but I can't come up with any ideas how to make it smoothly. 
May be some kind of function that you can pass to `setup_aiohttp_apispec` that will transform validation error body to format that user needs

**Comment by maximdanilchenko** [comment]
Hi!

Yes, it would be nice to have such feature. I had some plans to implement something like it (using [this](https://webargs.readthedocs.io/en/latest/quickstart.html#error-handling)).

As for now you can catch `web.HTTPUnprocessableEntity` (it is raised by webargs by default) error with your middleware and respond with whatever code and body you want. Like this:
```python
@web.middleware
async def my_middleware(request, handler):
    try:
        return await handler(request)
    except web.HTTPUnprocessableEntity:
        return web.json_response({'error': 'my custom error text'}, status=400)


app.middlewares.extend(
    [
        my_middleware,  # Catch exception by your own, format it and respond to client
        validation_middleware,
    ]
)
```
