### ISSUE TITLE
ValueError: dictionary update sequence element #0 has length 3; 2 is required

### ISSUE THREAD

**Issue by v-v-vishnevskiy** [maximdanilchenko/aiohttp-apispec#55]
This happens when I try to send something like this in body:
```javascript
[
  {"name": "John"},
  {"name": "Max"}
]
```
with appropriate request schema.

The error in this line https://github.com/maximdanilchenko/aiohttp-apispec/blame/master/aiohttp_apispec/middlewares.py#L37
`kwargs` is dictionary and can't update with list or tuple.

**Comment by v-v-vishnevskiy** [comment]
And in which cases may have several request schemas?

**Comment by maximdanilchenko** [comment]
In my opinion it is more correct and clear to have a name for each value in request body.
Like this:
```python
class Person(Schema):
    name = fields.String()

class ManyPersons(Schema):
    persons = fields.Nested(Person, many=True)
```
Now you can use ManyPersons schema in `@request_schema` decorator and body of your request will be like:
```
{
    "persons": [
      {"name": "John"},
      {"name": "Max"}
    ]
}
```

I think that it is more understandable approach for API users.

I will think about your case as well. I will make a patch to fix it.

**Comment by georgw777** [comment]
This error also occurs when [deserialising to objects](https://marshmallow.readthedocs.io/en/3.0/quickstart.html#deserializing-to-objects).

For example:
```python

class SomeObject(typing.NamedTuple):
    x: int
    y: int


class SomeObjectSchema(Schema):
    x = fields.Int()
    y = fields.Int()

    @post_load
    def make_object(self, data: dict):
        return SomeObject(**data)

@request_schema(SomeObjectSchema())
async def index(request):
     # ...
```

**Comment by georgw777** [comment]
PR #57 fixes this for me, but I'm not sure if that solves @v-v-vishnevskiy's exact problem too.
