### ISSUE TITLE
There is exists any way to generate swagger.json file by not starting an app?

### ISSUE THREAD

**Issue by v-v-vishnevskiy** [maximdanilchenko/aiohttp-apispec#56]
I mean I need to generate `swagger.json` in my .gitlab-ci.yml and send it to some service...
Need some method similar to `AiohttpApiSpec._register()`, but returns only `dict` with generated swagger info.

**Comment by maximdanilchenko** [comment]
After calling `_register()` you will find it in `app["swagger_dict"]`.
But be careful, it is private method. So it can be changed somedays.

Simplest and most correct way is to start an app before it and just get it from `app["swagger_dict"]` or with http get.

**Comment by v-v-vishnevskiy** [comment]
No, I don't need to start an app because in `cleanup_ctx` may occur heavy logic like downloading 500Mb ML model or bigger...
Need some way to get swagger.json without running web.Application. And I can't calling `_register()` because it is protected method and as you say it can be changed somedays.

Any idea?)

**Comment by maximdanilchenko** [comment]
Some ideas:
- Use `_register()` and freeze the library version in your requirements (it is must-have for all production projects).
- Use subapp for api logic and start it without starting parent app.
- Use some ENV/config variables to control your heavy logic.

**Comment by maximdanilchenko** [comment]
@v-v-vishnevskiy Now you have can do it! Use parameter `in_place=True`
```python
setup_aiohttp_apispec(app, ..., in_place=True)
```
But be sure all routes are added to router. Added in `1.4.0`
