### ISSUE TITLE
Swagger docs only show one parameter schema

### ISSUE THREAD

**Issue by ParkerD559** [maximdanilchenko/aiohttp-apispec#58]
## Summary
Since `__apispec__["parameters"]` is [no longer used](https://github.com/maximdanilchenko/aiohttp-apispec/commit/12716dd43f4c39c810265a9e539dff78c9a4cb78#diff-008c6084053ff20de7ba83dff616c9d5L96) in `request_schema`, and `__apispec__["schema"]` [is used](https://github.com/maximdanilchenko/aiohttp-apispec/blob/master/aiohttp_apispec/aiohttp_apispec.py#L116) for generating the `swagger.json`, the schema of only the first added parameter is shown in the swagger docs.

## Example
https://repl.it/repls/UrbanMushyMp3

### What Happened
As you can see in the output from the above link, the `swagger_dict` only contains the `headers` schema, even though both `body` and `headers` schemas were provided.

### Expected
The `parameters` list would contain both the `headers` and `body` schemas.

**Comment by maximdanilchenko** [comment]
I will release this fix in nearby future.
