### ISSUE TITLE
How can I generate multiple swagger.json

### ISSUE THREAD

**Issue by deterok** [maximdanilchenko/aiohttp-apispec#79]
I would like to generate different `swagger.json` for `/api/v1/swagger.json` and `/api/v2/swagger.json`. How can I do it?

**Comment by maximdanilchenko** [comment]
Hi!

You can do it using [subapps](https://docs.aiohttp.org/en/stable/web_advanced.html#nested-applications). Because of mounting some variables to Application object this is the only way to achieve it for now. By the way, subapps pattern is pretty nice for dividing api on different versions.

**Comment by deterok** [comment]
Thanks!
