### ISSUE TITLE
Does this package follow semantic versioning?

### ISSUE THREAD

**Issue by alvassin** [maximdanilchenko/aiohttp-apispec#85]
Does this package follow [semantic versioning](https://semver.org) ([PEP 440](https://www.python.org/dev/peps/pep-0440/#semantic-versioning))? 
Is it safe to use ~= requirement operator?
```
aiohttp-apispec~=2.1.0
```

**Comment by maximdanilchenko** [comment]
@alvassin yes, it is safe. All changes are backwards compatible. If there will be any breaking changes it will be in new major versions. Also warnings (deprecated etc) will be added before it.

**Comment by alvassin** [comment]
if you don't mind, I've added mention to README about that, to make easier decision for developers how to specify project version as a dependency.

**Comment by maximdanilchenko** [comment]
@alvassin, that's cool! Thank you!
