### ISSUE TITLE
adding example field to request_schema

### ISSUE THREAD

**Issue by Niccolum** [maximdanilchenko/aiohttp-apispec#89]
So, i see, that decorator `@request_schema` doesn't have `example` field (it not pass to `options`)
So, I can offer the following solution:
```
def request_schema(schema, locations=None, put_into=None, **kwargs):
...
    if not locations:
        locations = kwargs.pop("location", None)
...
options = {
    "required": kwargs.pop("required", False),
    **kwargs
}
```

If you agree with me and can do it or if you let me do PR - please, reply
If examples already can passed to `@docs` or `@request_schema` - please, adding this to docs

**Comment by maximdanilchenko** [comment]
@Niccolum, yes, you can do PR.

**Comment by Niccolum** [comment]
I see it is not so simple.
I will try to fix this problem.
I will report the result later

**Comment by maximdanilchenko** [comment]
Ok. Please, tell results. I will help or make changes by myself if needed

**Comment by Niccolum** [comment]
So, Actually, I have a problem.
I found how to correctly transfer examples, I found where, but so far I am at a loss how to transfer them to definitions

So, my changes now [in my local fork](https://github.com/Niccolum/aiohttp-apispec/commit/99c8a7be509a5d3a6574fcfb6d95ac4a6d15a2c9):

P.S. fix here also https://github.com/maximdanilchenko/aiohttp-apispec/issues/67
P.P.S. added 3.8 support to setup.py (it's working on it, i check)
P.P.P.S. I understand that this is not enough for PR. Can you help me for solution this problem, @maximdanilchenko ? I know apispec marshmallow ext badly =(
P.P.P.P.S All tests passed now

**Comment by Niccolum** [comment]
UPD:
Found hack solution. Please, can you help me to create from it normal solution?)
https://github.com/Niccolum/aiohttp-apispec/commit/781d864e871d0e80e72cad3105413e03580cc1a4

**Comment by Niccolum** [comment]
Of course, need add tests for new functionality
I adding it later.

**Comment by Niccolum** [comment]
I'm working on it, writing some tests and I have a question.
Do you think it is normal that an example that was intended for only one endpoint appears in the ref scheme, and, accordingly, it exists on all endpoints with this scheme. I don’t see in the swagger standard how to make sure that there is an example for only one endpoint, if it uses a ref scheme.

**Comment by Niccolum** [comment]
Finally, done my PR
@maximdanilchenko please, look at him, leave your feedback.

**Comment by Niccolum** [comment]
ping

**Comment by Niccolum** [comment]
PR 90 already merged. I think time to close issue

**Comment by sainoba** [comment]
Are there any plans to make a release to include this change?
